packages:
  - 'dsh-ide-layout'
  - 'dsh-question-pin'
  - 'dsh-lsp-core'
  - 'dsh-lsp-python'
  - 'dsh-lsp-typescript'
  - 'dsh-lsp-powershell'
  - 'dsh-lsp-java'
  - 'dsh-lsp-rust'

allowBuilds:
  node-pty: true
onlyBuiltDependencies:
  - node-pty
